language: android

jdk: oraclejdk8

sudo: false

android:
  components:
  - tools
  - platform-tools
  - build-tools-26.0.1
  - android-24
  - extra-android-support
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-21

script:
  - "./gradlew :app:assembleRelease"

before_install:
  - chmod +x gradlew

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'